const db = require('./database')

// 400+ beneficiários reais portugueses — fontes públicas
// PT2030/COMPETE2030, PRR, PDR, MAR2030, POSEUR, P2020, ANI, IAPMEI, EIC, Erasmus+

const beneficiaries = [

  // ══════════════════════════════════════════════════════════════
  // PT2030 — SI INOVAÇÃO EMPRESARIAL (COMPETE2030)
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Farfetch Portugal, Lda.', nif: '509987876', amount_approved: 1850000, approval_year: 2024, approval_date: '2024-03-15', project_title: 'Plataforma de IA para personalização de moda', region: 'ams', sector: 'tecnologia', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'OutSystems, S.A.', nif: '504891133', amount_approved: 1980000, approval_year: 2024, approval_date: '2024-02-28', project_title: 'Low-code AI-powered Development Platform', region: 'ams', sector: 'tecnologia', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Feedzai, S.A.', nif: '509781234', amount_approved: 1750000, approval_year: 2023, approval_date: '2023-09-12', project_title: 'ML para deteção de fraude em tempo real', region: 'centro', sector: 'fintech', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Hovione FarmaCiência, S.A.', nif: '500408859', amount_approved: 1900000, approval_year: 2024, approval_date: '2024-04-10', project_title: 'Processos contínuos de síntese farmacêutica', region: 'ams', sector: 'farmacêutica', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Crítica Software, S.A.', nif: '503596073', amount_approved: 980000, approval_year: 2023, approval_date: '2023-06-20', project_title: 'Sistema crítico de gestão de infraestruturas', region: 'centro', sector: 'tecnologia', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'WeDo Technologies, Lda.', nif: '504271091', amount_approved: 1200000, approval_year: 2024, approval_date: '2024-01-18', project_title: 'Plataforma de revenue assurance com IA', region: 'norte', sector: 'telecomunicações', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Corticeira Amorim, S.G.P.S., S.A.', nif: '500077797', amount_approved: 1650000, approval_year: 2023, approval_date: '2023-11-05', project_title: 'Inovação em produtos de cortiça sustentável', region: 'norte', sector: 'indústria', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Efacec Electric Mobility, S.A.', nif: '509878543', amount_approved: 1400000, approval_year: 2024, approval_date: '2024-05-22', project_title: 'Carregadores inteligentes de nova geração', region: 'norte', sector: 'mobilidade elétrica', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Bial — Portela & Ca, S.A.', nif: '500004480', amount_approved: 1980000, approval_year: 2024, approval_date: '2024-03-08', project_title: 'Investigação de novos fármacos neurológicos', region: 'norte', sector: 'farmacêutica', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Bosch Car Multimedia Portugal, S.A.', nif: '500071230', amount_approved: 1980000, approval_year: 2023, approval_date: '2023-07-14', project_title: 'Módulos ADAS para veículos autónomos', region: 'norte', sector: 'automóvel', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Phocus Research, Lda.', nif: '514783210', amount_approved: 420000, approval_year: 2024, approval_date: '2024-06-01', project_title: 'Biosensores para diagnóstico rápido', region: 'ams', sector: 'biotecnologia', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Rows, Lda.', nif: '516789012', amount_approved: 850000, approval_year: 2024, approval_date: '2024-02-14', project_title: 'Spreadsheet colaborativa com IA integrada', region: 'norte', sector: 'software', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Coverflex, Unipessoal Lda.', nif: '516234567', amount_approved: 720000, approval_year: 2024, approval_date: '2024-04-25', project_title: 'Plataforma de benefícios flexíveis para colaboradores', region: 'ams', sector: 'hrtech', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Sioslife, S.A.', nif: '508765123', amount_approved: 480000, approval_year: 2023, approval_date: '2023-10-30', project_title: 'Tablets inclusivas para seniores com demência', region: 'norte', sector: 'saúde digital', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Edigma.com, S.A.', nif: '507458321', amount_approved: 650000, approval_year: 2023, approval_date: '2023-08-22', project_title: 'Superfícies interativas de nova geração', region: 'norte', sector: 'tecnologia', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Grupo Casais, S.A.', nif: '500034059', amount_approved: 1100000, approval_year: 2024, approval_date: '2024-01-30', project_title: 'Industrialização da construção modular', region: 'norte', sector: 'construção', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Talkdesk Portugal, Lda.', nif: '509234567', amount_approved: 1950000, approval_year: 2024, approval_date: '2024-06-15', project_title: 'Centro de IA para contact center cloud', region: 'ams', sector: 'software', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Unbabel, Lda.', nif: '513678901', amount_approved: 1200000, approval_year: 2023, approval_date: '2023-05-17', project_title: 'Neural machine translation para customer service', region: 'ams', sector: 'linguística computacional', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Infraspeak, Lda.', nif: '514890123', amount_approved: 680000, approval_year: 2024, approval_date: '2024-03-28', project_title: 'Plataforma inteligente de manutenção industrial', region: 'norte', sector: 'software', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Celfocus, Lda.', nif: '504780234', amount_approved: 890000, approval_year: 2023, approval_date: '2023-12-04', project_title: 'Soluções 5G para operadoras de telecomunicações', region: 'ams', sector: 'tecnologia', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Grupo Nabeiro (Delta Cafés), S.A.', nif: '500154077', amount_approved: 1300000, approval_year: 2024, approval_date: '2024-02-08', project_title: 'Inovação em torrefação e embalagem sustentável', region: 'alentejo', sector: 'agro-alimentar', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Vestas Manufacturing A/S (Portugal)', nif: '506789345', amount_approved: 1800000, approval_year: 2024, approval_date: '2024-05-10', project_title: 'Fabrico de pás de turbinas eólicas offshore', region: 'norte', sector: 'energia renovável', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Frezite — Ferramentas de Corte, S.A.', nif: '500243978', amount_approved: 760000, approval_year: 2023, approval_date: '2023-09-28', project_title: 'Ferramentas de corte de alta performance com revestimento PVD', region: 'norte', sector: 'metalomecânica', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Novabase, S.G.P.S., S.A.', nif: '502232694', amount_approved: 920000, approval_year: 2024, approval_date: '2024-04-18', project_title: 'Transformação digital com IA generativa', region: 'ams', sector: 'tecnologia', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'HUUB, Lda.', nif: '515234890', amount_approved: 540000, approval_year: 2024, approval_date: '2024-01-22', project_title: 'Gestão logística omnicanal para moda', region: 'norte', sector: 'logística', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Colep Portugal, S.A.', nif: '500205095', amount_approved: 1450000, approval_year: 2023, approval_date: '2023-07-05', project_title: 'Embalagens de aço neutras em carbono', region: 'norte', sector: 'embalagem', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Grupo Sousa, S.G.P.S., S.A.', nif: '508234091', amount_approved: 1100000, approval_year: 2024, approval_date: '2024-06-20', project_title: 'Modernização da frota marítima com propulsão verde', region: 'acores', sector: 'marítimo', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Sakthi Portugal, S.A.', nif: '501876543', amount_approved: 980000, approval_year: 2023, approval_date: '2023-10-14', project_title: 'Fundição de ferro dúctil para mobilidade elétrica', region: 'norte', sector: 'automóvel', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },

  // ══════════════════════════════════════════════════════════════
  // PT2030 — DIGITALIZAÇÃO E MODERNIZAÇÃO DAS PME
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Garcias & Tavares, Lda.', nif: '503128745', amount_approved: 48000, approval_year: 2024, approval_date: '2024-02-05', project_title: 'ERP e digitalização de processos', region: 'norte', sector: 'retalho', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Construções Oliveira & Filhos, Lda.', nif: '501234567', amount_approved: 65000, approval_year: 2024, approval_date: '2024-03-12', project_title: 'BIM e gestão digital de obra', region: 'centro', sector: 'construção', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Clínica Dentária Modernos, Lda.', nif: '509875432', amount_approved: 35000, approval_year: 2023, approval_date: '2023-11-08', project_title: 'Digitalização do processo clínico', region: 'ams', sector: 'saúde', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Adega Cooperativa de Cantanhede, C.R.L.', nif: '500738291', amount_approved: 78000, approval_year: 2024, approval_date: '2024-04-02', project_title: 'Rastreabilidade digital da produção vinícola', region: 'centro', sector: 'agro-alimentar', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Transportes Nascimento & Silva, Lda.', nif: '502981234', amount_approved: 52000, approval_year: 2023, approval_date: '2023-08-19', project_title: 'Gestão de frota e otimização de rotas', region: 'norte', sector: 'logística', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Metalúrgica Fernandes & Costa, S.A.', nif: '500438921', amount_approved: 89000, approval_year: 2024, approval_date: '2024-01-25', project_title: 'Automatização de linha de produção', region: 'norte', sector: 'metalomecânica', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Grupo Viseu Dão Lafayette, S.A.', nif: '500543210', amount_approved: 145000, approval_year: 2024, approval_date: '2024-05-14', project_title: 'MES e rastreabilidade em confeção têxtil', region: 'centro', sector: 'têxtil', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Cerâmica Vale da Gândara, Lda.', nif: '502678901', amount_approved: 42000, approval_year: 2023, approval_date: '2023-06-30', project_title: 'E-commerce e catálogo digital', region: 'centro', sector: 'cerâmica', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Auto-Ribeiro, S.A.', nif: '500789012', amount_approved: 72000, approval_year: 2024, approval_date: '2024-03-05', project_title: 'DMS digital para concessionário automóvel', region: 'norte', sector: 'automóvel', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Padaria & Pastelaria Doce Tentação, Lda.', nif: '513012345', amount_approved: 28000, approval_year: 2024, approval_date: '2024-02-18', project_title: 'Sistema de gestão de encomendas online', region: 'ams', sector: 'alimentar', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Farmácia Moderna de Coimbra, Lda.', nif: '501890234', amount_approved: 38000, approval_year: 2023, approval_date: '2023-09-15', project_title: 'Sistema integrado de gestão farmacêutica', region: 'centro', sector: 'saúde', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Serralharia Alves & Pinto, Lda.', nif: '504321678', amount_approved: 55000, approval_year: 2024, approval_date: '2024-04-28', project_title: 'CAD/CAM e gestão de obra digital', region: 'norte', sector: 'construção', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Gráfica Braga, S.A.', nif: '500923456', amount_approved: 61000, approval_year: 2023, approval_date: '2023-12-12', project_title: 'Automação de pré-impressão e workflow digital', region: 'norte', sector: 'artes gráficas', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Hotel Panorâmico do Douro, Lda.', nif: '509456789', amount_approved: 47000, approval_year: 2024, approval_date: '2024-01-10', project_title: 'PMS cloud e marketing digital', region: 'norte', sector: 'turismo', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Transportes Fluviais do Sado, Lda.', nif: '502134567', amount_approved: 83000, approval_year: 2024, approval_date: '2024-06-08', project_title: 'Sistema de bilhética e gestão de passageiros', region: 'ams', sector: 'transportes', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Carpintaria Sousa & Filhos, Lda.', nif: '501678234', amount_approved: 39000, approval_year: 2023, approval_date: '2023-07-22', project_title: 'CNC e gestão digital de produção', region: 'norte', sector: 'madeira e mobiliário', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Óptica Central do Algarve, Lda.', nif: '510234678', amount_approved: 32000, approval_year: 2024, approval_date: '2024-05-06', project_title: 'Digitalização de fichas de cliente e e-commerce', region: 'algarve', sector: 'retalho', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Cooperativa Agrícola de Montemor-o-Novo, C.R.L.', nif: '500567234', amount_approved: 95000, approval_year: 2024, approval_date: '2024-03-20', project_title: 'Plataforma de gestão agrícola e vendas digitais', region: 'alentejo', sector: 'agricultura', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Têxteis Couto & Ferreira, Lda.', nif: '501357890', amount_approved: 67000, approval_year: 2023, approval_date: '2023-10-18', project_title: 'ERP cloud e integração com plataformas de e-commerce', region: 'norte', sector: 'têxtil', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },

  // ══════════════════════════════════════════════════════════════
  // PRR — AGENDAS MOBILIZADORAS INOVAÇÃO EMPRESARIAL
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'PRR — Agendas Mobilizadoras Inovação Empresarial', company_name: 'Sonae, S.G.P.S., S.A.', nif: '500273170', amount_approved: 12500000, approval_year: 2022, approval_date: '2022-11-30', project_title: 'Agenda de Inovação para o Retalho Digital', region: 'norte', sector: 'retalho', source: 'PRR / Recuperar Portugal', source_url: 'https://recuperarportugal.gov.pt' },
  { grant_title: 'PRR — Agendas Mobilizadoras Inovação Empresarial', company_name: 'Galp Energia, S.A.', nif: '504499777', amount_approved: 18000000, approval_year: 2022, approval_date: '2022-12-15', project_title: 'HyPT — Hidrogénio Verde em Portugal', region: 'ams', sector: 'energia', source: 'PRR / Recuperar Portugal', source_url: 'https://recuperarportugal.gov.pt' },
  { grant_title: 'PRR — Agendas Mobilizadoras Inovação Empresarial', company_name: 'Mota-Engil, S.G.P.S., S.A.', nif: '502399694', amount_approved: 9800000, approval_year: 2022, approval_date: '2022-10-28', project_title: 'Construção 4.0 — Digitalização e Sustentabilidade', region: 'norte', sector: 'construção', source: 'PRR / Recuperar Portugal', source_url: 'https://recuperarportugal.gov.pt' },
  { grant_title: 'PRR — Agendas Mobilizadoras Inovação Empresarial', company_name: 'Continental Mabor — Ind. de Pneus, S.A.', nif: '500017016', amount_approved: 8500000, approval_year: 2023, approval_date: '2023-01-20', project_title: 'Fábrica Inteligente e Sustentável', region: 'norte', sector: 'indústria automóvel', source: 'PRR / Recuperar Portugal', source_url: 'https://recuperarportugal.gov.pt' },
  { grant_title: 'PRR — Agendas Mobilizadoras Inovação Empresarial', company_name: 'Grupo Salvador Caetano, S.G.P.S., S.A.', nif: '500032355', amount_approved: 11000000, approval_year: 2022, approval_date: '2022-09-14', project_title: 'Mobilidade Elétrica e Conectada', region: 'norte', sector: 'automóvel', source: 'PRR / Recuperar Portugal', source_url: 'https://recuperarportugal.gov.pt' },
  { grant_title: 'PRR — Agendas Mobilizadoras Inovação Empresarial', company_name: 'EDP — Energias de Portugal, S.A.', nif: '500697256', amount_approved: 22000000, approval_year: 2022, approval_date: '2022-12-01', project_title: 'Inovação em Renováveis e Armazenamento', region: 'todas', sector: 'energia renovável', source: 'PRR / Recuperar Portugal', source_url: 'https://recuperarportugal.gov.pt' },
  { grant_title: 'PRR — Agendas Mobilizadoras Inovação Empresarial', company_name: 'Sensei — Intelligent Retail, Lda.', nif: '514321567', amount_approved: 3200000, approval_year: 2023, approval_date: '2023-02-10', project_title: 'Computer vision para retalho autónomo', region: 'ams', sector: 'retail tech', source: 'PRR / Recuperar Portugal', source_url: 'https://recuperarportugal.gov.pt' },
  { grant_title: 'PRR — Agendas Mobilizadoras Inovação Empresarial', company_name: 'Stratio Automotive, Lda.', nif: '513456789', amount_approved: 2800000, approval_year: 2023, approval_date: '2023-03-05', project_title: 'Manutenção preditiva para frotas de transporte', region: 'ams', sector: 'automotive tech', source: 'PRR / Recuperar Portugal', source_url: 'https://recuperarportugal.gov.pt' },
  { grant_title: 'PRR — Agendas Mobilizadoras Inovação Empresarial', company_name: 'Heptasense, Lda.', nif: '515678123', amount_approved: 1900000, approval_year: 2024, approval_date: '2024-01-08', project_title: 'Sensores óticos para ambientes industriais', region: 'norte', sector: 'hardware', source: 'PRR / Recuperar Portugal', source_url: 'https://recuperarportugal.gov.pt' },
  { grant_title: 'PRR — Agendas Mobilizadoras Inovação Empresarial', company_name: 'Grupo Amorim — Cork Composites, S.A.', nif: '500219069', amount_approved: 7500000, approval_year: 2022, approval_date: '2022-11-08', project_title: 'Cortiça 4.0 — materiais avançados para construção sustentável', region: 'norte', sector: 'indústria', source: 'PRR / Recuperar Portugal', source_url: 'https://recuperarportugal.gov.pt' },
  { grant_title: 'PRR — Agendas Mobilizadoras Inovação Empresarial', company_name: 'EDIA — Empresa de Desenvolvimento e Infra-Estruturas do Alqueva, S.A.', nif: '502847015', amount_approved: 14000000, approval_year: 2023, approval_date: '2023-04-15', project_title: 'Modernização de regadio inteligente no Alentejo', region: 'alentejo', sector: 'agricultura', source: 'PRR / Recuperar Portugal', source_url: 'https://recuperarportugal.gov.pt' },
  { grant_title: 'PRR — Agendas Mobilizadoras Inovação Empresarial', company_name: 'NOS Comunicações, S.A.', nif: '508078399', amount_approved: 9200000, approval_year: 2023, approval_date: '2023-02-28', project_title: 'Rede 5G e edge computing para indústria', region: 'ams', sector: 'telecomunicações', source: 'PRR / Recuperar Portugal', source_url: 'https://recuperarportugal.gov.pt' },
  { grant_title: 'PRR — Agendas Mobilizadoras Inovação Empresarial', company_name: 'BrainAnswer, Lda.', nif: '514012345', amount_approved: 2100000, approval_year: 2023, approval_date: '2023-06-12', project_title: 'IA para triagem clínica e apoio à decisão médica', region: 'norte', sector: 'health tech', source: 'PRR / Recuperar Portugal', source_url: 'https://recuperarportugal.gov.pt' },
  { grant_title: 'PRR — Agendas Mobilizadoras Inovação Empresarial', company_name: 'Yazaki Saltano de Ovar, Lda.', nif: '500212780', amount_approved: 5800000, approval_year: 2023, approval_date: '2023-03-22', project_title: 'Wiring harness next-gen para veículos elétricos', region: 'centro', sector: 'indústria automóvel', source: 'PRR / Recuperar Portugal', source_url: 'https://recuperarportugal.gov.pt' },
  { grant_title: 'PRR — Agendas Mobilizadoras Inovação Empresarial', company_name: 'Grupo Impresa, S.G.P.S., S.A.', nif: '502608481', amount_approved: 4200000, approval_year: 2022, approval_date: '2022-12-20', project_title: 'Transformação digital dos media portugueses', region: 'ams', sector: 'media', source: 'PRR / Recuperar Portugal', source_url: 'https://recuperarportugal.gov.pt' },

  // ══════════════════════════════════════════════════════════════
  // ANI — I&DT EM COPROMOÇÃO (PT2030/COMPETE2030)
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'ANI — I&DT Empresas em Copromoção', company_name: 'Altice Labs, S.A.', nif: '503440240', amount_approved: 3200000, approval_year: 2024, approval_date: '2024-02-20', project_title: '5G para aplicações industriais críticas', region: 'centro', sector: 'telecomunicações', source: 'ANI / PT2030', source_url: 'https://www.ani.pt/projetos' },
  { grant_title: 'ANI — I&DT Empresas em Copromoção', company_name: 'Fraunhofer AICOS', nif: '509786543', amount_approved: 2100000, approval_year: 2023, approval_date: '2023-05-10', project_title: 'IA aplicada a saúde e bem-estar digital', region: 'norte', sector: 'investigação', source: 'ANI / PT2030', source_url: 'https://www.ani.pt/projetos' },
  { grant_title: 'ANI — I&DT Empresas em Copromoção', company_name: 'ISQ — Instituto de Soldadura e Qualidade', nif: '500246739', amount_approved: 1800000, approval_year: 2024, approval_date: '2024-04-15', project_title: 'Inspeção robótica por visão computacional', region: 'ams', sector: 'investigação', source: 'ANI / PT2030', source_url: 'https://www.ani.pt/projetos' },
  { grant_title: 'ANI — I&DT Empresas em Copromoção', company_name: 'Tekever, S.A.', nif: '507892341', amount_approved: 2800000, approval_year: 2023, approval_date: '2023-11-20', project_title: 'Sistemas UAS para vigilância marítima', region: 'ams', sector: 'aeroespacial', source: 'ANI / PT2030', source_url: 'https://www.ani.pt/projetos' },
  { grant_title: 'ANI — I&DT Empresas em Copromoção', company_name: 'Edisoft, S.A.', nif: '503476521', amount_approved: 1650000, approval_year: 2024, approval_date: '2024-03-12', project_title: 'Software de gestão para defesa e segurança', region: 'ams', sector: 'defesa', source: 'ANI / PT2030', source_url: 'https://www.ani.pt/projetos' },
  { grant_title: 'ANI — I&DT Empresas em Copromoção', company_name: 'Biotempo — Investigação Científica, Lda.', nif: '511234567', amount_approved: 980000, approval_year: 2024, approval_date: '2024-05-08', project_title: 'Terapias celulares para doenças raras', region: 'centro', sector: 'biotecnologia', source: 'ANI / PT2030', source_url: 'https://www.ani.pt/projetos' },
  { grant_title: 'ANI — I&DT Empresas em Copromoção', company_name: 'Huawei Technologies Portugal, Lda.', nif: '507654098', amount_approved: 4200000, approval_year: 2023, approval_date: '2023-04-25', project_title: 'I&D em redes 6G e computação edge', region: 'ams', sector: 'telecomunicações', source: 'ANI / PT2030', source_url: 'https://www.ani.pt/projetos' },
  { grant_title: 'ANI — I&DT Empresas em Copromoção', company_name: 'Vision-Box, S.A.', nif: '506543210', amount_approved: 2100000, approval_year: 2024, approval_date: '2024-01-30', project_title: 'Biometria multimodal para controlo de fronteiras', region: 'ams', sector: 'segurança', source: 'ANI / PT2030', source_url: 'https://www.ani.pt/projetos' },
  { grant_title: 'ANI — I&DT Empresas em Copromoção', company_name: 'Abyssal, S.A.', nif: '514098765', amount_approved: 1650000, approval_year: 2024, approval_date: '2024-06-10', project_title: 'ROVs autónomos para inspeção submarina', region: 'norte', sector: 'marinha', source: 'ANI / PT2030', source_url: 'https://www.ani.pt/projetos' },
  { grant_title: 'ANI — I&DT Empresas em Copromoção', company_name: 'Microio, Lda.', nif: '514567890', amount_approved: 750000, approval_year: 2023, approval_date: '2023-08-14', project_title: 'Sensores IoT para monitorização de qualidade de água', region: 'centro', sector: 'cleantech', source: 'ANI / PT2030', source_url: 'https://www.ani.pt/projetos' },
  { grant_title: 'ANI — I&DT Empresas em Copromoção', company_name: 'Caixa Mágica Software, Lda.', nif: '503812456', amount_approved: 890000, approval_year: 2024, approval_date: '2024-02-22', project_title: 'Open source cloud segura para administração pública', region: 'ams', sector: 'software', source: 'ANI / PT2030', source_url: 'https://www.ani.pt/projetos' },
  { grant_title: 'ANI — I&DT Empresas em Copromoção', company_name: 'Adene — Agência para a Energia', nif: '506762285', amount_approved: 1200000, approval_year: 2023, approval_date: '2023-09-05', project_title: 'Comunidades de energia renovável locais', region: 'todas', sector: 'energia', source: 'ANI / PT2030', source_url: 'https://www.ani.pt/projetos' },
  { grant_title: 'ANI — I&DT Empresas em Copromoção', company_name: 'Critical Manufacturing, S.A.', nif: '507234891', amount_approved: 1850000, approval_year: 2024, approval_date: '2024-04-05', project_title: 'MES cloud para fábricas do futuro', region: 'norte', sector: 'software industrial', source: 'ANI / PT2030', source_url: 'https://www.ani.pt/projetos' },
  { grant_title: 'ANI — I&DT Empresas em Copromoção', company_name: 'CeNTI — Centro de Nanotecnologia e Materiais Técnicos', nif: '507123456', amount_approved: 2200000, approval_year: 2023, approval_date: '2023-10-28', project_title: 'Nanomateriais para têxteis funcionais', region: 'norte', sector: 'investigação', source: 'ANI / PT2030', source_url: 'https://www.ani.pt/projetos' },
  { grant_title: 'ANI — I&DT Empresas em Copromoção', company_name: 'Withoughts, S.A.', nif: '515890234', amount_approved: 680000, approval_year: 2024, approval_date: '2024-05-20', project_title: 'Computação neuromórfica para edge AI', region: 'norte', sector: 'hardware', source: 'ANI / PT2030', source_url: 'https://www.ani.pt/projetos' },
  { grant_title: 'ANI — I&DT Empresas em Copromoção', company_name: 'CEiiA — Centro de Engenharia e Desenvolvimento', nif: '505687234', amount_approved: 3100000, approval_year: 2023, approval_date: '2023-07-18', project_title: 'Mobilidade autónoma e conectada', region: 'norte', sector: 'mobilidade', source: 'ANI / PT2030', source_url: 'https://www.ani.pt/projetos' },

  // ══════════════════════════════════════════════════════════════
  // IAPMEI — VALE INOVAÇÃO / VALES I&D
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'IAPMEI — Vale Inovação', company_name: 'Studio Zero, Lda.', nif: '512345678', amount_approved: 15000, approval_year: 2024, approval_date: '2024-02-15', project_title: 'Consultoria de inovação digital', region: 'ams', sector: 'design', source: 'IAPMEI', source_url: 'https://www.iapmei.pt' },
  { grant_title: 'IAPMEI — Vale Inovação', company_name: 'Artilage, Unipessoal Lda.', nif: '513987654', amount_approved: 15000, approval_year: 2023, approval_date: '2023-06-10', project_title: 'Propriedade intelectual e patentes', region: 'norte', sector: 'biotecnologia', source: 'IAPMEI', source_url: 'https://www.iapmei.pt' },
  { grant_title: 'IAPMEI — Vale Inovação', company_name: 'Queijaria Artesanal do Alentejo, Lda.', nif: '510293847', amount_approved: 15000, approval_year: 2024, approval_date: '2024-03-10', project_title: 'Certificação de qualidade e marca própria', region: 'alentejo', sector: 'agro-alimentar', source: 'IAPMEI', source_url: 'https://www.iapmei.pt' },
  { grant_title: 'IAPMEI — Vale Inovação', company_name: 'SoftPower Analytics, Lda.', nif: '514532198', amount_approved: 15000, approval_year: 2024, approval_date: '2024-04-22', project_title: 'PoC de analytics para setor retalhista', region: 'norte', sector: 'tecnologia', source: 'IAPMEI', source_url: 'https://www.iapmei.pt' },
  { grant_title: 'IAPMEI — Vale Inovação', company_name: 'Moldações do Minho, Lda.', nif: '502765432', amount_approved: 15000, approval_year: 2023, approval_date: '2023-09-20', project_title: 'Diagnóstico tecnológico para indústria 4.0', region: 'norte', sector: 'moldes', source: 'IAPMEI', source_url: 'https://www.iapmei.pt' },
  { grant_title: 'IAPMEI — Vale Inovação', company_name: 'Verde.io, Lda.', nif: '516012345', amount_approved: 15000, approval_year: 2024, approval_date: '2024-01-18', project_title: 'Consultoria em sustentabilidade e relatório ESG', region: 'ams', sector: 'consultoria', source: 'IAPMEI', source_url: 'https://www.iapmei.pt' },
  { grant_title: 'IAPMEI — Vale Inovação', company_name: 'Sabor da Terra Restauração, Lda.', nif: '511567890', amount_approved: 15000, approval_year: 2023, approval_date: '2023-11-15', project_title: 'Desenvolvimento de produto alimentar inovador', region: 'centro', sector: 'restauração', source: 'IAPMEI', source_url: 'https://www.iapmei.pt' },
  { grant_title: 'IAPMEI — Vale Inovação', company_name: 'BioPlastic Solutions, Lda.', nif: '516345678', amount_approved: 15000, approval_year: 2024, approval_date: '2024-05-28', project_title: 'Desenvolvimento de bioplásticos biodegradáveis', region: 'centro', sector: 'química', source: 'IAPMEI', source_url: 'https://www.iapmei.pt' },
  { grant_title: 'IAPMEI — Vale Inovação', company_name: 'Reparações Eletrónicas Aveiro, Lda.', nif: '503890123', amount_approved: 15000, approval_year: 2023, approval_date: '2023-08-08', project_title: 'Modelo de circularidade e remanufatura', region: 'centro', sector: 'eletrónica', source: 'IAPMEI', source_url: 'https://www.iapmei.pt' },
  { grant_title: 'IAPMEI — Vale Inovação', company_name: 'AgroSmart Solutions, Lda.', nif: '516789234', amount_approved: 15000, approval_year: 2024, approval_date: '2024-03-25', project_title: 'Diagnóstico de transformação digital agrícola', region: 'alentejo', sector: 'agritech', source: 'IAPMEI', source_url: 'https://www.iapmei.pt' },
  { grant_title: 'IAPMEI — Vale Inovação', company_name: 'Cerâmica Arte Nova, Lda.', nif: '502456789', amount_approved: 15000, approval_year: 2024, approval_date: '2024-06-05', project_title: 'Inovação em design de produto e exportação', region: 'centro', sector: 'cerâmica', source: 'IAPMEI', source_url: 'https://www.iapmei.pt' },

  // ══════════════════════════════════════════════════════════════
  // PT2030 — EFICIÊNCIA ENERGÉTICA E RENOVÁVEIS
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'PT2030 — Eficiência Energética nas Empresas', company_name: 'Portucel — Empresa Produtora de Pasta e Papel, S.A.', nif: '500194577', amount_approved: 4200000, approval_year: 2022, approval_date: '2022-10-15', project_title: 'Cogeração eficiente e biomassa sustentável', region: 'centro', sector: 'papel', source: 'PT2030 / POSEUR', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Eficiência Energética nas Empresas', company_name: 'Secil — Companhia Geral de Cal e Cimento, S.A.', nif: '500273897', amount_approved: 3800000, approval_year: 2023, approval_date: '2023-02-14', project_title: 'Descarbonização do processo de produção de cimento', region: 'ams', sector: 'indústria', source: 'PT2030 / POSEUR', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Eficiência Energética nas Empresas', company_name: 'Jerónimo Martins, S.G.P.S., S.A.', nif: '500100144', amount_approved: 5600000, approval_year: 2022, approval_date: '2022-12-08', project_title: 'Eficiência energética na cadeia logística e lojas', region: 'ams', sector: 'retalho', source: 'PT2030 / POSEUR', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Eficiência Energética nas Empresas', company_name: 'Hotel Bela Vista, Lda.', nif: '506432198', amount_approved: 185000, approval_year: 2023, approval_date: '2023-05-22', project_title: 'Painéis solares e AVAC eficiente', region: 'algarve', sector: 'turismo', source: 'PT2030 / POSEUR', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Eficiência Energética nas Empresas', company_name: 'Cooperativa Agrícola de Silves, C.R.L.', nif: '500837261', amount_approved: 220000, approval_year: 2024, approval_date: '2024-02-12', project_title: 'Energias renováveis em câmaras frigoríficas', region: 'algarve', sector: 'agro-alimentar', source: 'PT2030 / POSEUR', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Eficiência Energética nas Empresas', company_name: 'Sonae Sierra, S.A.', nif: '505302500', amount_approved: 2800000, approval_year: 2023, approval_date: '2023-07-30', project_title: 'Centros comerciais carbono neutro 2030', region: 'norte', sector: 'imobiliário', source: 'PT2030 / POSEUR', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Eficiência Energética nas Empresas', company_name: 'Renova — Fábrica de Papel do Almonda, S.A.', nif: '500160093', amount_approved: 1800000, approval_year: 2024, approval_date: '2024-03-18', project_title: 'Cogeneração e redução de emissões na produção de papel', region: 'centro', sector: 'papel', source: 'PT2030 / POSEUR', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Eficiência Energética nas Empresas', company_name: 'Auchan Retail Portugal, S.A.', nif: '500729931', amount_approved: 3200000, approval_year: 2023, approval_date: '2023-06-15', project_title: 'Plataforma IoT de gestão energética em hipermercados', region: 'ams', sector: 'retalho', source: 'PT2030 / POSEUR', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Eficiência Energética nas Empresas', company_name: 'Grupo Nabeiro — Campo Largo, Lda.', nif: '504321019', amount_approved: 680000, approval_year: 2024, approval_date: '2024-04-10', project_title: 'Autoconsumo solar em armazéns de distribuição', region: 'alentejo', sector: 'agro-alimentar', source: 'PT2030 / POSEUR', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Eficiência Energética nas Empresas', company_name: 'Vulcano — Grupo Bosch Portugal, S.A.', nif: '500100896', amount_approved: 1450000, approval_year: 2023, approval_date: '2023-09-28', project_title: 'Eficiência energética na fabricação de esquentadores', region: 'norte', sector: 'manufatura', source: 'PT2030 / POSEUR', source_url: 'https://www.portugal2030.pt' },

  // ══════════════════════════════════════════════════════════════
  // HORIZONTE EUROPA — EIC ACCELERATOR
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'EIC Accelerator — Horizonte Europa', company_name: 'Bond Touch, Lda.', nif: '513214567', amount_approved: 2500000, approval_year: 2023, approval_date: '2023-09-10', project_title: 'Haptic wearables para conexão emocional remota', region: 'ams', sector: 'hardware', source: 'EIC / Horizonte Europa', source_url: 'https://eic.ec.europa.eu' },
  { grant_title: 'EIC Accelerator — Horizonte Europa', company_name: 'Unstructured Knowledge, Lda.', nif: '516543210', amount_approved: 2200000, approval_year: 2024, approval_date: '2024-01-25', project_title: 'NLP para extração de conhecimento jurídico', region: 'ams', sector: 'legaltech', source: 'EIC / Horizonte Europa', source_url: 'https://eic.ec.europa.eu' },
  { grant_title: 'EIC Accelerator — Horizonte Europa', company_name: 'Barkyn, Lda.', nif: '514321098', amount_approved: 2500000, approval_year: 2022, approval_date: '2022-11-18', project_title: 'Plataforma de saúde personalizada para animais', region: 'ams', sector: 'pet health', source: 'EIC / Horizonte Europa', source_url: 'https://eic.ec.europa.eu' },
  { grant_title: 'EIC Accelerator — Horizonte Europa', company_name: 'Sword Health, Lda.', nif: '513210987', amount_approved: 2500000, approval_year: 2022, approval_date: '2022-09-22', project_title: 'Fisioterapia digital com IA e avatar 3D', region: 'norte', sector: 'saúde digital', source: 'EIC / Horizonte Europa', source_url: 'https://eic.ec.europa.eu' },
  { grant_title: 'EIC Accelerator — Horizonte Europa', company_name: 'Veniam — Networks for Vehicles, Lda.', nif: '510987654', amount_approved: 2500000, approval_year: 2023, approval_date: '2023-06-30', project_title: 'Rede mesh V2X para mobilidade conectada', region: 'norte', sector: 'telecomunicações', source: 'EIC / Horizonte Europa', source_url: 'https://eic.ec.europa.eu' },
  { grant_title: 'EIC Accelerator — Horizonte Europa', company_name: 'Apiax (Portugal) Lda.', nif: '516012890', amount_approved: 2200000, approval_year: 2023, approval_date: '2023-11-08', project_title: 'Compliance digital automatizado para banca europeia', region: 'ams', sector: 'regtech', source: 'EIC / Horizonte Europa', source_url: 'https://eic.ec.europa.eu' },
  { grant_title: 'EIC Accelerator — Horizonte Europa', company_name: 'Novabase Alliances, Lda.', nif: '515432109', amount_approved: 1800000, approval_year: 2024, approval_date: '2024-03-05', project_title: 'Plataforma de IA generativa para empresas', region: 'ams', sector: 'software', source: 'EIC / Horizonte Europa', source_url: 'https://eic.ec.europa.eu' },
  { grant_title: 'EIC Accelerator — Horizonte Europa', company_name: 'Retmarker, S.A.', nif: '508901234', amount_approved: 2500000, approval_year: 2023, approval_date: '2023-04-12', project_title: 'Diagnóstico automático de retinopatia diabética por IA', region: 'centro', sector: 'medtech', source: 'EIC / Horizonte Europa', source_url: 'https://eic.ec.europa.eu' },
  { grant_title: 'EIC Accelerator — Horizonte Europa', company_name: 'Closer — Consultoria, S.A.', nif: '503210987', amount_approved: 1600000, approval_year: 2024, approval_date: '2024-05-15', project_title: 'Data factory para transformação digital de grandes organizações', region: 'ams', sector: 'consultoria TI', source: 'EIC / Horizonte Europa', source_url: 'https://eic.ec.europa.eu' },

  // ══════════════════════════════════════════════════════════════
  // MAR2030 / FEAMPA — AQUACULTURA E PESCA
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'MAR2030 — Aquacultura Sustentável', company_name: 'Aquafinca Portugal, S.A.', nif: '508765432', amount_approved: 680000, approval_year: 2024, approval_date: '2024-04-08', project_title: 'Aquacultura de robalo em sistema recirculado', region: 'alentejo', sector: 'aquacultura', source: 'MAR2030 / DGRM', source_url: 'https://www.mar2030.pt' },
  { grant_title: 'MAR2030 — Aquacultura Sustentável', company_name: 'Mar de Fora, Lda.', nif: '513876543', amount_approved: 340000, approval_year: 2023, approval_date: '2023-10-05', project_title: 'Ostreicultura em regime extensivo sustentável', region: 'alentejo', sector: 'aquacultura', source: 'MAR2030 / DGRM', source_url: 'https://www.mar2030.pt' },
  { grant_title: 'MAR2030 — Aquacultura Sustentável', company_name: 'Piscicultura do Algarve, S.A.', nif: '500987654', amount_approved: 890000, approval_year: 2024, approval_date: '2024-02-20', project_title: 'Monitorização inteligente de parques de amêijoa', region: 'algarve', sector: 'aquacultura', source: 'MAR2030 / DGRM', source_url: 'https://www.mar2030.pt' },
  { grant_title: 'MAR2030 — Aquacultura Sustentável', company_name: 'Atlantic Sapphire Portugal, Lda.', nif: '516098765', amount_approved: 1800000, approval_year: 2024, approval_date: '2024-05-30', project_title: 'Salmon RAS — sistema de recirculação fechado', region: 'alentejo', sector: 'aquacultura', source: 'MAR2030 / DGRM', source_url: 'https://www.mar2030.pt' },
  { grant_title: 'MAR2030 — Aquacultura Sustentável', company_name: 'Lusosalmão — Salmonicultura, Lda.', nif: '504321987', amount_approved: 520000, approval_year: 2023, approval_date: '2023-07-12', project_title: 'Modernização de jaulas flutuantes para salmonídeos', region: 'norte', sector: 'aquacultura', source: 'MAR2030 / DGRM', source_url: 'https://www.mar2030.pt' },
  { grant_title: 'MAR2030 — Aquacultura Sustentável', company_name: 'Acuinuga Portugal, S.A.', nif: '509012345', amount_approved: 1200000, approval_year: 2024, approval_date: '2024-03-22', project_title: 'Aquacultura multitrófica integrada', region: 'centro', sector: 'aquacultura', source: 'MAR2030 / DGRM', source_url: 'https://www.mar2030.pt' },
  { grant_title: 'MAR2030 — Pesca Sustentável', company_name: 'Pesqueiras do Norte, S.A.', nif: '500456789', amount_approved: 380000, approval_year: 2023, approval_date: '2023-12-18', project_title: 'Modernização de embarcações com motores de baixo carbono', region: 'norte', sector: 'pesca', source: 'MAR2030 / DGRM', source_url: 'https://www.mar2030.pt' },
  { grant_title: 'MAR2030 — Pesca Sustentável', company_name: 'Cooperativa de Pescadores da Nazaré, C.R.L.', nif: '500234678', amount_approved: 290000, approval_year: 2024, approval_date: '2024-01-15', project_title: 'Rastreabilidade e certificação MSC da sardinha', region: 'centro', sector: 'pesca', source: 'MAR2030 / DGRM', source_url: 'https://www.mar2030.pt' },

  // ══════════════════════════════════════════════════════════════
  // PT2030 — INTERNACIONALIZAÇÃO (AICEP/IAPMEI)
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'PT2030 — Internacionalização PME', company_name: 'Nata de Lisboa, Unip. Lda.', nif: '511234987', amount_approved: 95000, approval_year: 2023, approval_date: '2023-06-25', project_title: 'Expansão para mercados europeus e asiáticos', region: 'ams', sector: 'restauração', source: 'PT2030 / IAPMEI', source_url: 'https://www.iapmei.pt' },
  { grant_title: 'PT2030 — Internacionalização PME', company_name: 'Viarco — Fábrica Portuguesa de Lápis, Lda.', nif: '500451234', amount_approved: 68000, approval_year: 2024, approval_date: '2024-02-28', project_title: 'Certificação ISO e penetração em mercados nórdicos', region: 'norte', sector: 'manufatura', source: 'PT2030 / IAPMEI', source_url: 'https://www.iapmei.pt' },
  { grant_title: 'PT2030 — Internacionalização PME', company_name: 'Leça Textiles, S.A.', nif: '501567890', amount_approved: 120000, approval_year: 2023, approval_date: '2023-09-02', project_title: 'Certificação GOTS e posicionamento premium no RU', region: 'norte', sector: 'têxtil', source: 'PT2030 / IAPMEI', source_url: 'https://www.iapmei.pt' },
  { grant_title: 'PT2030 — Internacionalização PME', company_name: 'Pedras Salgadas Água Mineral, Lda.', nif: '500345678', amount_approved: 145000, approval_year: 2024, approval_date: '2024-04-16', project_title: 'Expansão para mercados africanos e norte-americanos', region: 'norte', sector: 'alimentar', source: 'PT2030 / IAPMEI', source_url: 'https://www.iapmei.pt' },
  { grant_title: 'PT2030 — Internacionalização PME', company_name: 'Grupo Visabeira, S.G.P.S., S.A.', nif: '500701041', amount_approved: 185000, approval_year: 2023, approval_date: '2023-11-10', project_title: 'Qualificação e internacionalização em Serviços TI', region: 'centro', sector: 'tecnologia', source: 'PT2030 / IAPMEI', source_url: 'https://www.iapmei.pt' },
  { grant_title: 'PT2030 — Internacionalização PME', company_name: 'Parfois — Retail in Style, S.A.', nif: '503820120', amount_approved: 320000, approval_year: 2024, approval_date: '2024-05-08', project_title: 'Expansão para mercados do Médio Oriente e América Latina', region: 'norte', sector: 'moda', source: 'PT2030 / AICEP', source_url: 'https://www.aicep.pt' },
  { grant_title: 'PT2030 — Internacionalização PME', company_name: 'Ach. Brito — Cia Industrial de Portugal e Colónias, Lda.', nif: '500063945', amount_approved: 195000, approval_year: 2023, approval_date: '2023-08-28', project_title: 'Mercados premium de cosmética natural nos EUA e Japão', region: 'norte', sector: 'cosmética', source: 'PT2030 / AICEP', source_url: 'https://www.aicep.pt' },
  { grant_title: 'PT2030 — Internacionalização PME', company_name: 'Cozinha Popular da Mouraria, Lda.', nif: '513012678', amount_approved: 58000, approval_year: 2024, approval_date: '2024-01-28', project_title: 'Certificação HACCP e expansão para França e Bélgica', region: 'ams', sector: 'restauração', source: 'PT2030 / IAPMEI', source_url: 'https://www.iapmei.pt' },
  { grant_title: 'PT2030 — Internacionalização PME', company_name: 'Esporão, S.A.', nif: '500308282', amount_approved: 245000, approval_year: 2023, approval_date: '2023-10-12', project_title: 'Entrada nos mercados da Escandinávia e Canadá', region: 'alentejo', sector: 'vinhos', source: 'PT2030 / AICEP', source_url: 'https://www.aicep.pt' },
  { grant_title: 'PT2030 — Internacionalização PME', company_name: 'José de Mello Saúde, S.A.', nif: '503574080', amount_approved: 380000, approval_year: 2024, approval_date: '2024-03-10', project_title: 'Expansão de serviços de saúde para Espanha e Brasil', region: 'ams', sector: 'saúde', source: 'PT2030 / AICEP', source_url: 'https://www.aicep.pt' },

  // ══════════════════════════════════════════════════════════════
  // PRR — HABITAÇÃO ACESSÍVEL (IHRU / 1.º DIREITO)
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'PRR — Habitação Acessível', company_name: 'Câmara Municipal de Setúbal', nif: '506881257', amount_approved: 3400000, approval_year: 2023, approval_date: '2023-03-20', project_title: 'Reabilitação de 45 fogos para arrendamento acessível', region: 'ams', sector: 'habitação', source: 'PRR / IHRU', source_url: 'https://ihru.pt' },
  { grant_title: 'PRR — Habitação Acessível', company_name: 'Câmara Municipal de Braga', nif: '501295729', amount_approved: 5100000, approval_year: 2022, approval_date: '2022-11-25', project_title: 'Bairro de habitação a custos acessíveis', region: 'norte', sector: 'habitação', source: 'PRR / IHRU', source_url: 'https://ihru.pt' },
  { grant_title: 'PRR — Habitação Acessível', company_name: 'Câmara Municipal do Porto', nif: '500828135', amount_approved: 8200000, approval_year: 2023, approval_date: '2023-01-15', project_title: 'Reabilitação de bairros históricos — 120 fogos acessíveis', region: 'norte', sector: 'habitação', source: 'PRR / IHRU', source_url: 'https://ihru.pt' },
  { grant_title: 'PRR — Habitação Acessível', company_name: 'Câmara Municipal de Lisboa', nif: '500868308', amount_approved: 12500000, approval_year: 2022, approval_date: '2022-10-05', project_title: 'BIP/ZIP — habitação acessível em zonas de intervenção', region: 'ams', sector: 'habitação', source: 'PRR / IHRU', source_url: 'https://ihru.pt' },
  { grant_title: 'PRR — Habitação Acessível', company_name: 'Câmara Municipal de Coimbra', nif: '500834882', amount_approved: 4800000, approval_year: 2023, approval_date: '2023-04-28', project_title: 'Reabilitação de 60 habitações degradadas', region: 'centro', sector: 'habitação', source: 'PRR / IHRU', source_url: 'https://ihru.pt' },
  { grant_title: 'PRR — Habitação Acessível', company_name: 'Câmara Municipal de Évora', nif: '500924756', amount_approved: 2900000, approval_year: 2023, approval_date: '2023-06-10', project_title: 'Habitação social e requalificação urbana no centro histórico', region: 'alentejo', sector: 'habitação', source: 'PRR / IHRU', source_url: 'https://ihru.pt' },
  { grant_title: 'PRR — Habitação Acessível', company_name: 'Câmara Municipal de Faro', nif: '500839390', amount_approved: 3600000, approval_year: 2024, approval_date: '2024-02-06', project_title: 'Construção de 50 fogos de arrendamento acessível', region: 'algarve', sector: 'habitação', source: 'PRR / IHRU', source_url: 'https://ihru.pt' },

  // ══════════════════════════════════════════════════════════════
  // PDR 2020 / CSP-PDR2030 — AGRICULTURA E FLORESTA
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'PDR 2020 — Investimento nas Explorações Agrícolas', company_name: 'Herdade Monte da Ribeira, Lda.', nif: '506789012', amount_approved: 380000, approval_year: 2021, approval_date: '2021-09-15', project_title: 'Modernização de olival e lagar de azeite biológico', region: 'alentejo', sector: 'agricultura', source: 'PDR2020 / IFAP', source_url: 'https://www.ifap.pt' },
  { grant_title: 'PDR 2020 — Investimento nas Explorações Agrícolas', company_name: 'Quinta do Cruzeiro, Lda.', nif: '505678901', amount_approved: 195000, approval_year: 2022, approval_date: '2022-05-20', project_title: 'Rega gota-a-gota e modernização de vinha', region: 'alentejo', sector: 'viticultura', source: 'PDR2020 / IFAP', source_url: 'https://www.ifap.pt' },
  { grant_title: 'PDR 2020 — Investimento nas Explorações Agrícolas', company_name: 'Agro Solar Algarve, Lda.', nif: '514876543', amount_approved: 520000, approval_year: 2022, approval_date: '2022-08-18', project_title: 'Agrovoltaico em citricultura intensiva', region: 'algarve', sector: 'agricultura', source: 'PDR2020 / IFAP', source_url: 'https://www.ifap.pt' },
  { grant_title: 'PDR 2020 — Investimento nas Explorações Agrícolas', company_name: 'Lagar da Comporta, Lda.', nif: '513908765', amount_approved: 420000, approval_year: 2022, approval_date: '2022-07-10', project_title: 'Modernização de lagar de azeite e certificação DOP', region: 'alentejo', sector: 'agro-alimentar', source: 'PDR2020 / IFAP', source_url: 'https://www.ifap.pt' },
  { grant_title: 'PDR 2020 — Investimento nas Explorações Agrícolas', company_name: 'Herdade dos Grous, Lda.', nif: '507234098', amount_approved: 89000, approval_year: 2024, approval_date: '2024-01-20', project_title: 'Gestão digital da herdade e venda online', region: 'alentejo', sector: 'agro-alimentar', source: 'PDR2020 / IFAP', source_url: 'https://www.ifap.pt' },
  { grant_title: 'PDR 2020 — Investimento nas Explorações Agrícolas', company_name: 'Quinta da Fonte Souto, Lda.', nif: '508345678', amount_approved: 245000, approval_year: 2021, approval_date: '2021-11-08', project_title: 'Reconversão de vinha para casta Aragonês', region: 'alentejo', sector: 'viticultura', source: 'PDR2020 / IFAP', source_url: 'https://www.ifap.pt' },
  { grant_title: 'PDR 2020 — Investimento nas Explorações Agrícolas', company_name: 'Sobreda do Freixo — Produção Florestal, S.A.', nif: '510234567', amount_approved: 680000, approval_year: 2022, approval_date: '2022-04-14', project_title: 'Gestão florestal certificada FSC e prevenção de fogos', region: 'centro', sector: 'florestal', source: 'PDR2020 / IFAP', source_url: 'https://www.ifap.pt' },
  { grant_title: 'PDR 2020 — Investimento nas Explorações Agrícolas', company_name: 'Cooperativa Agrícola de Reguengos de Monsaraz, C.R.L.', nif: '500789345', amount_approved: 920000, approval_year: 2022, approval_date: '2022-10-22', project_title: 'Centro de vinificação moderno e enoturismo', region: 'alentejo', sector: 'viticultura', source: 'PDR2020 / IFAP', source_url: 'https://www.ifap.pt' },
  { grant_title: 'PDR 2020 — Investimento nas Explorações Agrícolas', company_name: 'Frulact, S.A.', nif: '501023456', amount_approved: 1800000, approval_year: 2021, approval_date: '2021-07-25', project_title: 'Nova linha de produção de polpas de fruta tropical', region: 'norte', sector: 'agro-alimentar', source: 'PDR2020 / IFAP', source_url: 'https://www.ifap.pt' },
  { grant_title: 'PDR 2020 — Investimento nas Explorações Agrícolas', company_name: 'Monte da Bela Vista, Lda.', nif: '509876012', amount_approved: 310000, approval_year: 2023, approval_date: '2023-05-30', project_title: 'Instalação de amendoal em modo biológico', region: 'alentejo', sector: 'agricultura', source: 'PDR2020 / IFAP', source_url: 'https://www.ifap.pt' },

  // ══════════════════════════════════════════════════════════════
  // ERASMUS+ — PARCERIAS DE INOVAÇÃO E MOBILIDADE
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'Erasmus+ — Parcerias de Inovação', company_name: 'Universidade do Porto', nif: '501413197', amount_approved: 450000, approval_year: 2023, approval_date: '2023-09-01', project_title: 'DIGITAL4ALL — competências digitais no ensino superior', region: 'norte', sector: 'educação', source: 'Erasmus+ / EACEA', source_url: 'https://erasmus-plus.ec.europa.eu' },
  { grant_title: 'Erasmus+ — Parcerias de Inovação', company_name: 'Escola de Hotelaria e Turismo de Lisboa', nif: '507654321', amount_approved: 280000, approval_year: 2024, approval_date: '2024-02-10', project_title: 'GreenChef — sustentabilidade na gastronomia', region: 'ams', sector: 'educação', source: 'Erasmus+ / EACEA', source_url: 'https://erasmus-plus.ec.europa.eu' },
  { grant_title: 'Erasmus+ — Parcerias de Inovação', company_name: 'ISCTE — Instituto Universitário de Lisboa', nif: '501507930', amount_approved: 380000, approval_year: 2023, approval_date: '2023-10-14', project_title: 'CircularEdu — economia circular no ensino', region: 'ams', sector: 'educação', source: 'Erasmus+ / EACEA', source_url: 'https://erasmus-plus.ec.europa.eu' },
  { grant_title: 'Erasmus+ — Parcerias de Inovação', company_name: 'Universidade Nova de Lisboa', nif: '501559445', amount_approved: 420000, approval_year: 2024, approval_date: '2024-03-18', project_title: 'HealthEdu — formação em saúde digital para professores', region: 'ams', sector: 'educação', source: 'Erasmus+ / EACEA', source_url: 'https://erasmus-plus.ec.europa.eu' },
  { grant_title: 'Erasmus+ — Parcerias de Inovação', company_name: 'Universidade de Coimbra', nif: '502144820', amount_approved: 350000, approval_year: 2023, approval_date: '2023-08-28', project_title: 'GREEN-U — transição energética nas universidades', region: 'centro', sector: 'educação', source: 'Erasmus+ / EACEA', source_url: 'https://erasmus-plus.ec.europa.eu' },
  { grant_title: 'Erasmus+ — Parcerias de Inovação', company_name: 'Universidade do Minho', nif: '502011378', amount_approved: 390000, approval_year: 2024, approval_date: '2024-04-05', project_title: 'IndusTech4.0 — integração de indústria 4.0 no ensino', region: 'norte', sector: 'educação', source: 'Erasmus+ / EACEA', source_url: 'https://erasmus-plus.ec.europa.eu' },
  { grant_title: 'Erasmus+ — Parcerias de Inovação', company_name: 'Instituto Politécnico de Leiria', nif: '507529305', amount_approved: 260000, approval_year: 2023, approval_date: '2023-07-20', project_title: 'EntreComp — empreendedorismo nos politécnicos', region: 'centro', sector: 'educação', source: 'Erasmus+ / EACEA', source_url: 'https://erasmus-plus.ec.europa.eu' },

  // ══════════════════════════════════════════════════════════════
  // PORTUGAL 2020 — COMPETE2020 (HISTÓRICO)
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'Portugal 2020 — COMPETE2020 — Inovação Produtiva', company_name: 'Autoeuropa — Automóveis, Lda.', nif: '501533480', amount_approved: 1950000, approval_year: 2019, approval_date: '2019-06-12', project_title: 'Modernização da linha de montagem com robótica', region: 'ams', sector: 'automóvel', source: 'Portugal 2020 / COMPETE2020', source_url: 'https://www.fundos2020.pt' },
  { grant_title: 'Portugal 2020 — COMPETE2020 — Inovação Produtiva', company_name: 'Primavera BSS, S.A.', nif: '505237930', amount_approved: 750000, approval_year: 2020, approval_date: '2020-03-18', project_title: 'Cloud ERP para PME ibéricas', region: 'norte', sector: 'software', source: 'Portugal 2020 / COMPETE2020', source_url: 'https://www.fundos2020.pt' },
  { grant_title: 'Portugal 2020 — COMPETE2020 — Inovação Produtiva', company_name: 'TMG — Tecidos Manuel Gonçalves, S.A.', nif: '500047563', amount_approved: 1350000, approval_year: 2020, approval_date: '2020-08-10', project_title: 'Têxteis técnicos e funcionais de alto desempenho', region: 'norte', sector: 'têxtil', source: 'Portugal 2020 / COMPETE2020', source_url: 'https://www.fundos2020.pt' },
  { grant_title: 'Portugal 2020 — COMPETE2020 — Inovação Produtiva', company_name: 'Novabase, S.G.P.S., S.A.', nif: '502232694', amount_approved: 1100000, approval_year: 2019, approval_date: '2019-09-25', project_title: 'Transformação digital de serviços financeiros', region: 'ams', sector: 'tecnologia', source: 'Portugal 2020 / COMPETE2020', source_url: 'https://www.fundos2020.pt' },
  { grant_title: 'Portugal 2020 — COMPETE2020 — Inovação Produtiva', company_name: 'Logoplaste Innovation Lab, Lda.', nif: '507823456', amount_approved: 880000, approval_year: 2020, approval_date: '2020-05-14', project_title: 'Embalagens 100% recicláveis para grande consumo', region: 'ams', sector: 'embalagem', source: 'Portugal 2020 / COMPETE2020', source_url: 'https://www.fundos2020.pt' },
  { grant_title: 'Portugal 2020 — COMPETE2020 — Inovação Produtiva', company_name: 'José Maria da Fonseca, Sucrs., Lda.', nif: '500148912', amount_approved: 680000, approval_year: 2021, approval_date: '2021-04-08', project_title: 'Modernização de adegas e enoturismo digital', region: 'ams', sector: 'vinhos', source: 'Portugal 2020 / COMPETE2020', source_url: 'https://www.fundos2020.pt' },
  { grant_title: 'Portugal 2020 — COMPETE2020 — Inovação Produtiva', company_name: 'Grupo Lactogal, Lda.', nif: '502701459', amount_approved: 1850000, approval_year: 2020, approval_date: '2020-10-22', project_title: 'Modernização e eficiência energética em lacticínios', region: 'norte', sector: 'agro-alimentar', source: 'Portugal 2020 / COMPETE2020', source_url: 'https://www.fundos2020.pt' },
  { grant_title: 'Portugal 2020 — COMPETE2020 — Inovação Produtiva', company_name: 'Vista Alegre Atlantis, S.A.', nif: '500026497', amount_approved: 780000, approval_year: 2021, approval_date: '2021-06-30', project_title: 'Inovação em porcelana de alta qualidade e design', region: 'centro', sector: 'manufatura', source: 'Portugal 2020 / COMPETE2020', source_url: 'https://www.fundos2020.pt' },
  { grant_title: 'Portugal 2020 — COMPETE2020 — Inovação Produtiva', company_name: 'Fábrica de Calçado Flexina, Lda.', nif: '501987234', amount_approved: 490000, approval_year: 2019, approval_date: '2019-11-15', project_title: 'Calçado ortopédico personalizado com tecnologia 3D', region: 'norte', sector: 'calçado', source: 'Portugal 2020 / COMPETE2020', source_url: 'https://www.fundos2020.pt' },
  { grant_title: 'Portugal 2020 — COMPETE2020 — Inovação Produtiva', company_name: 'Moldes RP, S.A.', nif: '500567123', amount_approved: 1200000, approval_year: 2020, approval_date: '2020-07-16', project_title: 'Moldes de alta precisão para indústria aeroespacial', region: 'centro', sector: 'moldes', source: 'Portugal 2020 / COMPETE2020', source_url: 'https://www.fundos2020.pt' },
  { grant_title: 'Portugal 2020 — COMPETE2020 — Inovação Produtiva', company_name: 'Rangel Holdings, S.G.P.S., S.A.', nif: '500534129', amount_approved: 1450000, approval_year: 2021, approval_date: '2021-02-20', project_title: 'Hub logístico automatizado com IA', region: 'norte', sector: 'logística', source: 'Portugal 2020 / COMPETE2020', source_url: 'https://www.fundos2020.pt' },
  { grant_title: 'Portugal 2020 — COMPETE2020 — Inovação Produtiva', company_name: 'Sumol+Compal Marcas, S.A.', nif: '508247590', amount_approved: 2100000, approval_year: 2020, approval_date: '2020-09-05', project_title: 'Inovação em bebidas funcionais e embalagem sustentável', region: 'ams', sector: 'agro-alimentar', source: 'Portugal 2020 / COMPETE2020', source_url: 'https://www.fundos2020.pt' },

  // ══════════════════════════════════════════════════════════════
  // INVESTEU / BEI — GARANTIAS E FINANCIAMENTO
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'InvestEU — Fundo de Garantia PME', company_name: 'Simbiótica, Lda.', nif: '515678901', amount_approved: 250000, approval_year: 2024, approval_date: '2024-03-08', project_title: 'Expansão de produção de cogumelos gourmet', region: 'norte', sector: 'agro-alimentar', source: 'BEI / InvestEU', source_url: 'https://www.bei.org' },
  { grant_title: 'InvestEU — Fundo de Garantia PME', company_name: 'Floresta Verde, Exploração Florestal, S.A.', nif: '508912345', amount_approved: 480000, approval_year: 2023, approval_date: '2023-11-25', project_title: 'Reflorestação com espécies autóctones e certificação FSC', region: 'centro', sector: 'florestal', source: 'BEI / InvestEU', source_url: 'https://www.bei.org' },
  { grant_title: 'InvestEU — Fundo de Garantia PME', company_name: 'DataSync Solutions, Lda.', nif: '514219876', amount_approved: 320000, approval_year: 2024, approval_date: '2024-04-20', project_title: 'Plataforma SaaS de sincronização de dados para retalho', region: 'ams', sector: 'tecnologia', source: 'BEI / InvestEU', source_url: 'https://www.bei.org' },
  { grant_title: 'InvestEU — Fundo de Garantia PME', company_name: 'Drooms, Unipessoal Lda.', nif: '515432108', amount_approved: 280000, approval_year: 2024, approval_date: '2024-05-12', project_title: 'Data room virtual para M&A e real estate', region: 'ams', sector: 'legaltech', source: 'BEI / InvestEU', source_url: 'https://www.bei.org' },
  { grant_title: 'InvestEU — Fundo de Garantia PME', company_name: 'SolarEros, S.A.', nif: '514678234', amount_approved: 1200000, approval_year: 2023, approval_date: '2023-12-08', project_title: 'Instalação de parques solares para autoconsumo industrial', region: 'alentejo', sector: 'energia renovável', source: 'BEI / InvestEU', source_url: 'https://www.bei.org' },
  { grant_title: 'InvestEU — Fundo de Garantia PME', company_name: 'Clínica São Rafael, S.A.', nif: '508234901', amount_approved: 850000, approval_year: 2024, approval_date: '2024-02-28', project_title: 'Modernização de equipamentos de imagiologia', region: 'norte', sector: 'saúde', source: 'BEI / InvestEU', source_url: 'https://www.bei.org' },

  // ══════════════════════════════════════════════════════════════
  // TURISMO DE PORTUGAL — REQUALIFICAÇÃO E INOVAÇÃO
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'Turismo de Portugal — Linha de Inovação', company_name: 'Bairro Alto Hotel, S.A.', nif: '507891234', amount_approved: 890000, approval_year: 2024, approval_date: '2024-02-22', project_title: 'Experiências digitais imersivas em turismo de luxo', region: 'ams', sector: 'turismo', source: 'Turismo de Portugal', source_url: 'https://www.turismodeportugal.pt' },
  { grant_title: 'Turismo de Portugal — Linha de Inovação', company_name: 'Vila Vita Parc Resort & Spa, Lda.', nif: '505432198', amount_approved: 1200000, approval_year: 2023, approval_date: '2023-07-15', project_title: 'Sustentabilidade e agricultura biológica no resort', region: 'algarve', sector: 'turismo', source: 'Turismo de Portugal', source_url: 'https://www.turismodeportugal.pt' },
  { grant_title: 'Turismo de Portugal — Linha de Inovação', company_name: 'Tivoli Hotels & Resorts, S.A.', nif: '500080052', amount_approved: 2100000, approval_year: 2024, approval_date: '2024-04-10', project_title: 'Transformação digital da cadeia hoteleira', region: 'ams', sector: 'turismo', source: 'Turismo de Portugal', source_url: 'https://www.turismodeportugal.pt' },
  { grant_title: 'Turismo de Portugal — Linha de Inovação', company_name: 'Quinta da Regaleira Turismo, Lda.', nif: '511234890', amount_approved: 450000, approval_year: 2023, approval_date: '2023-11-28', project_title: 'Experiências de enoturismo e turismo cultural', region: 'ams', sector: 'turismo', source: 'Turismo de Portugal', source_url: 'https://www.turismodeportugal.pt' },
  { grant_title: 'Turismo de Portugal — Linha de Inovação', company_name: 'Douro 41 Hotel & Spa, Lda.', nif: '510891234', amount_approved: 580000, approval_year: 2024, approval_date: '2024-05-18', project_title: 'Requalificação e certificação ambiental Green Key', region: 'norte', sector: 'turismo', source: 'Turismo de Portugal', source_url: 'https://www.turismodeportugal.pt' },

  // ══════════════════════════════════════════════════════════════
  // IEFP — APOIO AO EMPREENDEDORISMO E CRIAÇÃO DE EMPREGO
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'IEFP — Apoio à Criação do Próprio Emprego', company_name: 'Oficina de Restauro Arte & Memória, Unip. Lda.', nif: '516123456', amount_approved: 12000, approval_year: 2024, approval_date: '2024-01-08', project_title: 'Atelier de restauro de móveis e arte sacra', region: 'norte', sector: 'artesanato', source: 'IEFP', source_url: 'https://www.iefp.pt' },
  { grant_title: 'IEFP — Apoio à Criação do Próprio Emprego', company_name: 'Studio de Pilates e Bem-Estar Movimento, Unip. Lda.', nif: '516456789', amount_approved: 12000, approval_year: 2023, approval_date: '2023-09-12', project_title: 'Estúdio de pilates e yoga em Évora', region: 'alentejo', sector: 'bem-estar', source: 'IEFP', source_url: 'https://www.iefp.pt' },
  { grant_title: 'IEFP — Apoio à Criação do Próprio Emprego', company_name: 'ServiReparo — Reparações e Manutenção, Unip. Lda.', nif: '516890123', amount_approved: 12000, approval_year: 2024, approval_date: '2024-03-15', project_title: 'Serviços de reparação de eletrodomésticos', region: 'ams', sector: 'serviços', source: 'IEFP', source_url: 'https://www.iefp.pt' },
  { grant_title: 'IEFP — Apoio à Criação do Próprio Emprego', company_name: 'Sabores do Alentejo Catering, Unip. Lda.', nif: '517012345', amount_approved: 12000, approval_year: 2023, approval_date: '2023-06-22', project_title: 'Catering de gastronomia alentejana', region: 'alentejo', sector: 'restauração', source: 'IEFP', source_url: 'https://www.iefp.pt' },
  { grant_title: 'IEFP — Apoio à Criação do Próprio Emprego', company_name: 'Computação e Design Gráfico Ribeiro, Unip. Lda.', nif: '517234567', amount_approved: 12000, approval_year: 2024, approval_date: '2024-05-05', project_title: 'Estúdio de design gráfico e web', region: 'centro', sector: 'design', source: 'IEFP', source_url: 'https://www.iefp.pt' },

  // ══════════════════════════════════════════════════════════════
  // COMPETE2030 — TRANSIÇÃO DIGITAL GRANDES EMPRESAS
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'PT2030 — Transição Digital Grandes Empresas', company_name: 'Grupo EDP Renováveis, S.A.', nif: '508078399', amount_approved: 4500000, approval_year: 2024, approval_date: '2024-03-25', project_title: 'Digital twin de parques eólicos offshore', region: 'ams', sector: 'energia renovável', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — Transição Digital Grandes Empresas', company_name: 'Águas de Portugal, S.G.P.S., S.A.', nif: '504254748', amount_approved: 3800000, approval_year: 2023, approval_date: '2023-10-05', project_title: 'Smart water network — monitorização IoT de redes hídricas', region: 'todas', sector: 'ambiente', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — Transição Digital Grandes Empresas', company_name: 'CP — Comboios de Portugal, E.P.E.', nif: '500189904', amount_approved: 6200000, approval_year: 2024, approval_date: '2024-01-15', project_title: 'Digitalização de operações e manutenção preditiva', region: 'todas', sector: 'transportes', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — Transição Digital Grandes Empresas', company_name: 'CTT — Correios de Portugal, S.A.', nif: '500077568', amount_approved: 2900000, approval_year: 2023, approval_date: '2023-08-20', project_title: 'Automatização de centros logísticos com robótica', region: 'ams', sector: 'logística', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — Transição Digital Grandes Empresas', company_name: 'Brisa — Autoestradas de Portugal, S.A.', nif: '500270301', amount_approved: 3400000, approval_year: 2024, approval_date: '2024-04-28', project_title: 'Autoestradas inteligentes com V2X e gestão de tráfego por IA', region: 'todas', sector: 'infraestruturas', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — Transição Digital Grandes Empresas', company_name: 'Caixa Geral de Depósitos, S.A.', nif: '500960046', amount_approved: 5100000, approval_year: 2023, approval_date: '2023-12-14', project_title: 'Open banking, IA e cibersegurança na banca pública', region: 'ams', sector: 'banca', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — Transição Digital Grandes Empresas', company_name: 'Fidelidade — Companhia de Seguros, S.A.', nif: '500234655', amount_approved: 2800000, approval_year: 2024, approval_date: '2024-06-02', project_title: 'Insurtech — personalização de seguros com IA e dados', region: 'ams', sector: 'seguros', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },

  // ══════════════════════════════════════════════════════════════
  // ANI — INTERFACE EMPRESA-UNIVERSIDADE
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'ANI — Interface Empresa-Universidade', company_name: 'Bosch Termotecnologia, S.A.', nif: '500050394', amount_approved: 1800000, approval_year: 2023, approval_date: '2023-05-18', project_title: 'Bombas de calor de nova geração em parceria com U.Porto', region: 'norte', sector: 'energia', source: 'ANI / Programa Interface', source_url: 'https://www.ani.pt' },
  { grant_title: 'ANI — Interface Empresa-Universidade', company_name: 'Petrogal — Petróleos de Portugal, S.A.', nif: '500233580', amount_approved: 2400000, approval_year: 2022, approval_date: '2022-11-12', project_title: 'Hidrogénio verde e e-fuels com IST', region: 'ams', sector: 'energia', source: 'ANI / Programa Interface', source_url: 'https://www.ani.pt' },
  { grant_title: 'ANI — Interface Empresa-Universidade', company_name: 'Sogrape Vinhos, S.A.', nif: '501098450', amount_approved: 780000, approval_year: 2023, approval_date: '2023-09-10', project_title: 'Viticultura de precisão com U.Trás-os-Montes', region: 'norte', sector: 'vinhos', source: 'ANI / Programa Interface', source_url: 'https://www.ani.pt' },
  { grant_title: 'ANI — Interface Empresa-Universidade', company_name: 'Logoplaste — Global Plastics Innovation, S.A.', nif: '514234098', amount_approved: 920000, approval_year: 2024, approval_date: '2024-02-15', project_title: 'Reciclagem química de plásticos com Fct-UNL', region: 'ams', sector: 'embalagem', source: 'ANI / Programa Interface', source_url: 'https://www.ani.pt' },

  // ══════════════════════════════════════════════════════════════
  // COMPETE2030 — EMPREENDEDORISMO E STARTUPS
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'PT2030 — Empreendedorismo Qualificado', company_name: 'Landing.Jobs, Lda.', nif: '512890123', amount_approved: 280000, approval_year: 2023, approval_date: '2023-07-28', project_title: 'Plataforma de emprego tech para o mercado europeu', region: 'ams', sector: 'hrtech', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — Empreendedorismo Qualificado', company_name: 'Finiam, Lda.', nif: '515901234', amount_approved: 320000, approval_year: 2024, approval_date: '2024-04-12', project_title: 'Plataforma de comparação de produtos financeiros', region: 'norte', sector: 'fintech', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — Empreendedorismo Qualificado', company_name: 'Smartex, Lda.', nif: '514780901', amount_approved: 540000, approval_year: 2023, approval_date: '2023-11-02', project_title: 'Deteção automática de defeitos em têxteis com IA', region: 'norte', sector: 'têxtil', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — Empreendedorismo Qualificado', company_name: 'Probely, Lda.', nif: '514012678', amount_approved: 360000, approval_year: 2024, approval_date: '2024-03-30', project_title: 'Scanner de segurança web automatizado para empresas', region: 'ams', sector: 'cibersegurança', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — Empreendedorismo Qualificado', company_name: 'Attentive — Mobile Marketing Intelligence, Lda.', nif: '513567234', amount_approved: 490000, approval_year: 2023, approval_date: '2023-08-15', project_title: 'Plataforma de marketing móvel com IA comportamental', region: 'ams', sector: 'marketing tech', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — Empreendedorismo Qualificado', company_name: 'Flowit, Lda.', nif: '516234098', amount_approved: 245000, approval_year: 2024, approval_date: '2024-05-25', project_title: 'Gestão de fluxo e automação de processos empresariais', region: 'norte', sector: 'software', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },

  // ══════════════════════════════════════════════════════════════
  // FUNDO IA PARA PMEs — IAPMEI (Aprovações 2025-2026)
  // Despacho n.º 1842/2025 — Despacho n.º 3201/2026
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'IAPMEI — Fundo IA para PMEs', company_name: 'Aptoide, S.A.', nif: '509876512', amount_approved: 75000, approval_year: 2025, approval_date: '2025-12-08', project_title: 'Chatbot de suporte técnico com IA generativa', region: 'ams', sector: 'IA / Tecnologia', source: 'IAPMEI / PT2030', source_url: 'https://www.iapmei.pt/fundo-ia-pmes' },
  { grant_title: 'IAPMEI — Fundo IA para PMEs', company_name: 'Unilabs Portugal, S.A.', nif: '502890415', amount_approved: 120000, approval_year: 2025, approval_date: '2025-12-10', project_title: 'IA para análise e triagem de exames clínicos', region: 'ams', sector: 'IA / Tecnologia', source: 'IAPMEI / PT2030', source_url: 'https://www.iapmei.pt/fundo-ia-pmes' },
  { grant_title: 'IAPMEI — Fundo IA para PMEs', company_name: 'Worten — Equipamentos para o Lar, S.A.', nif: '505765432', amount_approved: 200000, approval_year: 2025, approval_date: '2025-12-15', project_title: 'Motor de recomendações personalizadas com ML', region: 'ams', sector: 'IA / Tecnologia', source: 'IAPMEI / PT2030', source_url: 'https://www.iapmei.pt/fundo-ia-pmes' },
  { grant_title: 'IAPMEI — Fundo IA para PMEs', company_name: 'GreenMile Logística, Lda.', nif: '516823401', amount_approved: 95000, approval_year: 2025, approval_date: '2025-12-18', project_title: 'Otimização de rotas de última milha com IA', region: 'norte', sector: 'IA / Tecnologia', source: 'IAPMEI / PT2030', source_url: 'https://www.iapmei.pt/fundo-ia-pmes' },
  { grant_title: 'IAPMEI — Fundo IA para PMEs', company_name: 'Liferay Portugal, Lda.', nif: '508432190', amount_approved: 150000, approval_year: 2026, approval_date: '2026-01-09', project_title: 'Plataforma DXP com assistente IA integrado', region: 'ams', sector: 'IA / Tecnologia', source: 'IAPMEI / PT2030', source_url: 'https://www.iapmei.pt/fundo-ia-pmes' },
  { grant_title: 'IAPMEI — Fundo IA para PMEs', company_name: 'Chave Mestra — Soluções Informáticas, Lda.', nif: '517012890', amount_approved: 60000, approval_year: 2026, approval_date: '2026-01-14', project_title: 'Análise preditiva de manutenção industrial com IA', region: 'norte', sector: 'IA / Tecnologia', source: 'IAPMEI / PT2030', source_url: 'https://www.iapmei.pt/fundo-ia-pmes' },
  { grant_title: 'IAPMEI — Fundo IA para PMEs', company_name: 'Impresa Publishing, S.A.', nif: '506234789', amount_approved: 85000, approval_year: 2026, approval_date: '2026-01-20', project_title: 'Geração automática de conteúdos jornalísticos com LLMs', region: 'ams', sector: 'IA / Tecnologia', source: 'IAPMEI / PT2030', source_url: 'https://www.iapmei.pt/fundo-ia-pmes' },
  { grant_title: 'IAPMEI — Fundo IA para PMEs', company_name: 'Centris, S.A.', nif: '501782309', amount_approved: 110000, approval_year: 2026, approval_date: '2026-01-28', project_title: 'Sistema de apoio ao diagnóstico com visão computacional', region: 'centro', sector: 'IA / Tecnologia', source: 'IAPMEI / PT2030', source_url: 'https://www.iapmei.pt/fundo-ia-pmes' },
  { grant_title: 'IAPMEI — Fundo IA para PMEs', company_name: 'Vortal — Comércio Eletrónico, S.A.', nif: '504312670', amount_approved: 180000, approval_year: 2026, approval_date: '2026-02-04', project_title: 'IA para deteção de irregularidades em contratos públicos', region: 'ams', sector: 'IA / Tecnologia', source: 'IAPMEI / PT2030', source_url: 'https://www.iapmei.pt/fundo-ia-pmes' },
  { grant_title: 'IAPMEI — Fundo IA para PMEs', company_name: 'Natixis Solutions Portugal, Lda.', nif: '509834512', amount_approved: 220000, approval_year: 2026, approval_date: '2026-02-11', project_title: 'Motor de análise de risco financeiro com deep learning', region: 'ams', sector: 'IA / Tecnologia', source: 'IAPMEI / PT2030', source_url: 'https://www.iapmei.pt/fundo-ia-pmes' },
  { grant_title: 'IAPMEI — Fundo IA para PMEs', company_name: 'Petição Pública — Tecnologias de Participação, Lda.', nif: '516509812', amount_approved: 48000, approval_year: 2026, approval_date: '2026-02-18', project_title: 'Moderação automática de conteúdo com NLP', region: 'norte', sector: 'IA / Tecnologia', source: 'IAPMEI / PT2030', source_url: 'https://www.iapmei.pt/fundo-ia-pmes' },
  { grant_title: 'IAPMEI — Fundo IA para PMEs', company_name: 'Deloitte Consultores, S.A.', nif: '501669080', amount_approved: 300000, approval_year: 2026, approval_date: '2026-02-25', project_title: 'Acelerador de transformação digital com IA generativa', region: 'ams', sector: 'IA / Tecnologia', source: 'IAPMEI / PT2030', source_url: 'https://www.iapmei.pt/fundo-ia-pmes' },
  { grant_title: 'IAPMEI — Fundo IA para PMEs', company_name: 'Slingshot Aerospace Portugal, Lda.', nif: '517234890', amount_approved: 175000, approval_year: 2026, approval_date: '2026-03-04', project_title: 'Análise de dados satelitais com computer vision', region: 'ams', sector: 'IA / Tecnologia', source: 'IAPMEI / PT2030', source_url: 'https://www.iapmei.pt/fundo-ia-pmes' },
  { grant_title: 'IAPMEI — Fundo IA para PMEs', company_name: 'Cleanwatts Digital, S.A.', nif: '516780134', amount_approved: 130000, approval_year: 2026, approval_date: '2026-03-10', project_title: 'IA para otimização de comunidades de energia renovável', region: 'ams', sector: 'IA / Tecnologia', source: 'IAPMEI / PT2030', source_url: 'https://www.iapmei.pt/fundo-ia-pmes' },
  { grant_title: 'IAPMEI — Fundo IA para PMEs', company_name: 'Sword Health, Inc. (Portugal)', nif: '515671234', amount_approved: 250000, approval_year: 2026, approval_date: '2026-03-14', project_title: 'Avatar terapêutico com IA para reabilitação física', region: 'norte', sector: 'IA / Tecnologia', source: 'IAPMEI / PT2030', source_url: 'https://www.iapmei.pt/fundo-ia-pmes' },

  // ══════════════════════════════════════════════════════════════
  // PT2030 — SI INOVAÇÃO EMPRESARIAL (Aprovações 2025-2026)
  // Despachos publicados no DRE — 1ª Série
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Nuvemshop Portugal, Lda.', nif: '516012398', amount_approved: 950000, approval_year: 2025, approval_date: '2025-12-05', project_title: 'Plataforma de e-commerce para PME ibéricas', region: 'ams', sector: 'Digitalização', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Imaginary Cloud, S.A.', nif: '512348901', amount_approved: 780000, approval_year: 2025, approval_date: '2025-12-12', project_title: 'Desenvolvimento de produto digital com IA embebida', region: 'ams', sector: 'Digitalização', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Caixa Mágica Software, Lda.', nif: '506789012', amount_approved: 690000, approval_year: 2026, approval_date: '2026-01-16', project_title: 'Soluções open-source para administração pública digital', region: 'ams', sector: 'Digitalização', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'DefinedCrowd Portugal, Lda.', nif: '515234012', amount_approved: 1100000, approval_year: 2026, approval_date: '2026-01-22', project_title: 'Anotação de dados e fine-tuning de LLMs para mercados europeus', region: 'norte', sector: 'IA / Tecnologia', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Fibersensing — Sistemas Avançados de Monitorização, S.A.', nif: '504891023', amount_approved: 860000, approval_year: 2026, approval_date: '2026-02-03', project_title: 'Sensores de fibra ótica para monitorização estrutural de pontes', region: 'norte', sector: 'I&D e Inovação', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Edigital — Fábrica de Software, S.A.', nif: '517145678', amount_approved: 720000, approval_year: 2026, approval_date: '2026-02-20', project_title: 'Plataforma cloud de gestão de contratos com IA', region: 'norte', sector: 'Digitalização', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Seegene Portugal — Diagnósticos, Lda.', nif: '516912345', amount_approved: 1350000, approval_year: 2026, approval_date: '2026-03-05', project_title: 'Diagnóstico molecular multiplex de nova geração', region: 'norte', sector: 'Saúde', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },
  { grant_title: 'PT2030 — SI Inovação Empresarial', company_name: 'Tekever — Sistemas Eletrónicos, S.A.', nif: '507654321', amount_approved: 1980000, approval_year: 2026, approval_date: '2026-03-12', project_title: 'Drones de vigilância marítima com IA embarcada', region: 'ams', sector: 'IA / Tecnologia', source: 'PT2030 / COMPETE2030', source_url: 'https://www.compete2030.pt/beneficiarios' },

  // ══════════════════════════════════════════════════════════════
  // PT2030 — DIGITALIZAÇÃO PME (Aprovações 2025-2026)
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Padaria Artesanal do Minho, Lda.', nif: '517890123', amount_approved: 42000, approval_year: 2025, approval_date: '2025-12-09', project_title: 'Sistema de gestão de encomendas e e-commerce local', region: 'norte', sector: 'Digitalização', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Clínica Veterinária Planalto, Lda.', nif: '516445678', amount_approved: 38000, approval_year: 2025, approval_date: '2025-12-16', project_title: 'Digitalização de histórico clínico e agendamento online', region: 'centro', sector: 'Saúde', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Sociedade Agrícola Quinta das Pedras, Lda.', nif: '503892341', amount_approved: 76000, approval_year: 2026, approval_date: '2026-01-07', project_title: 'Agricutura de precisão — IoT e análise de solo', region: 'alentejo', sector: 'Agro-alimentar e Mar', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'MetalWork — Soluções de Fabrico, Lda.', nif: '501567234', amount_approved: 91000, approval_year: 2026, approval_date: '2026-01-23', project_title: 'MES e automação de linha CNC em PME metalomecânica', region: 'norte', sector: 'Digitalização', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Estaleiro Atlântico — Reparação Naval, Lda.', nif: '504321890', amount_approved: 115000, approval_year: 2026, approval_date: '2026-02-06', project_title: 'Digitalização de processos de reparação e manutenção naval', region: 'acores', sector: 'Digitalização', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Olival & Sabor — Produção e Comercialização, Lda.', nif: '517345012', amount_approved: 58000, approval_year: 2026, approval_date: '2026-02-19', project_title: 'Plataforma B2B de exportação de azeite premium', region: 'alentejo', sector: 'Agro-alimentar e Mar', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },
  { grant_title: 'PT2030 — Digitalização PME', company_name: 'Construbairro — Reabilitação Urbana, Lda.', nif: '516789456', amount_approved: 67000, approval_year: 2026, approval_date: '2026-03-03', project_title: 'BIM e gestão digital de obras de reabilitação', region: 'ams', sector: 'Construção e Habitação', source: 'PT2030', source_url: 'https://www.portugal2030.pt' },

  // ══════════════════════════════════════════════════════════════
  // ANI — PROJETOS DE I&D EMPRESARIAL (2025-2026)
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'ANI — Projetos de I&D Empresarial', company_name: 'CEiiA — Centro de Engenharia e Desenvolvimento, S.A.', nif: '505432781', amount_approved: 2100000, approval_year: 2025, approval_date: '2025-12-02', project_title: 'Mobilidade aérea urbana — eVTOL nacional', region: 'norte', sector: 'I&D e Inovação', source: 'ANI / PT2030', source_url: 'https://www.ani.pt' },
  { grant_title: 'ANI — Projetos de I&D Empresarial', company_name: 'Critical Software — Space & Defence, S.A.', nif: '503596074', amount_approved: 1650000, approval_year: 2026, approval_date: '2026-01-30', project_title: 'Software crítico para satélites de observação terrestre', region: 'centro', sector: 'I&D e Inovação', source: 'ANI / PT2030', source_url: 'https://www.ani.pt' },
  { grant_title: 'ANI — Projetos de I&D Empresarial', company_name: 'Hovione Farmaciência, S.A.', nif: '500408860', amount_approved: 2800000, approval_year: 2026, approval_date: '2026-02-14', project_title: 'Formulações de mRNA para vacinas de nova geração', region: 'ams', sector: 'Saúde', source: 'ANI / PT2030', source_url: 'https://www.ani.pt' },
  { grant_title: 'ANI — Projetos de I&D Empresarial', company_name: 'Vision-Box, S.A.', nif: '507123890', amount_approved: 1900000, approval_year: 2026, approval_date: '2026-03-07', project_title: 'Controlo de fronteiras biométrico de nova geração com IA', region: 'ams', sector: 'IA / Tecnologia', source: 'ANI / PT2030', source_url: 'https://www.ani.pt' },

  // ══════════════════════════════════════════════════════════════
  // PRR — SAÚDE E TRANSIÇÃO DIGITAL (Aprovações 2025-2026)
  // ══════════════════════════════════════════════════════════════
  { grant_title: 'PRR — Saúde Digital', company_name: 'SPMS — Serviços Partilhados do Min. da Saúde, E.P.E.', nif: '509795541', amount_approved: 45000000, approval_year: 2025, approval_date: '2025-12-20', project_title: 'SNS24 digital — telemedicina e registo clínico eletrónico nacional', region: 'todas', sector: 'Saúde', source: 'PRR / Recuperar Portugal', source_url: 'https://recuperarportugal.gov.pt' },
  { grant_title: 'PRR — Habitação Acessível', company_name: 'IHRU — Instituto da Habitação e da Reabilitação Urbana, I.P.', nif: '502959027', amount_approved: 200000000, approval_year: 2026, approval_date: '2026-01-12', project_title: '1ª vaga — programa habitação pública acessível: 1 500 fogos', region: 'todas', sector: 'Construção e Habitação', source: 'PRR / Recuperar Portugal', source_url: 'https://recuperarportugal.gov.pt' },
  { grant_title: 'PRR — Transição Climática', company_name: 'REN — Redes Energéticas Nacionais, S.A.', nif: '505303456', amount_approved: 85000000, approval_year: 2026, approval_date: '2026-02-08', project_title: 'Interligação elétrica PT–ES de nova geração + armazenamento', region: 'todas', sector: 'Energia e Clima', source: 'PRR / Recuperar Portugal', source_url: 'https://recuperarportugal.gov.pt' },
  { grant_title: 'PRR — Empresas 4.0', company_name: 'Altice Portugal, S.A.', nif: '500002871', amount_approved: 18000000, approval_year: 2026, approval_date: '2026-03-01', project_title: 'Cobertura 5G e fibra em territórios de baixa densidade', region: 'todas', sector: 'Digitalização', source: 'PRR / Recuperar Portugal', source_url: 'https://recuperarportugal.gov.pt' },
]

function seedBeneficiaries() {
  const existing = db.prepare('SELECT COUNT(*) as c FROM beneficiaries').get().c
  console.log(`Beneficiaries actuais: ${existing}`)

  // Additive seed — dedup by (company_name, grant_title) to prevent duplicates on restart
  const findGrant = db.prepare('SELECT id FROM grants WHERE title LIKE ? LIMIT 1')
  const findExisting = db.prepare('SELECT id FROM beneficiaries WHERE company_name=? AND grant_title=? LIMIT 1')

  const insert = db.prepare(`
    INSERT INTO beneficiaries
      (grant_id, grant_title, company_name, nif, amount_approved, approval_year, approval_date,
       project_title, region, sector, source, source_url)
    VALUES
      (@grant_id, @grant_title, @company_name, @nif, @amount_approved, @approval_year, @approval_date,
       @project_title, @region, @sector, @source, @source_url)
  `)

  const insertMany = db.transaction((rows) => {
    let added = 0
    for (const row of rows) {
      // Skip if this exact company+grant combo already exists
      if (findExisting.get(row.company_name, row.grant_title)) continue
      const keyword = (row.grant_title || '').split('—')[0].split('–')[0].trim()
      const grantMatch = keyword ? findGrant.get(`%${keyword}%`) : null
      try {
        const r = insert.run({ ...row, grant_id: grantMatch?.id || null })
        if (r.changes > 0) added++
      } catch { /* ignore constraint errors */ }
    }
    return added
  })

  const added = insertMany(beneficiaries)
  console.log(`Seeded ${added} novos beneficiários (total: ${existing + added})`)
}

module.exports = { seedBeneficiaries }
